### ISSUE TITLE
Reject bounds that aren't a rectangle

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-api#43]
Found when searching for a bug. This is actually probably a different bug to mine - mine involves missing locations, and this one produces extra locations - my guess is the logic for the response does an OR instead of AND when intersecting the bounds with location's coordinates, but adding `center` uses a different query - a less efficient one but on that happens to be correct - hence different responses?

Substitute the right api key into these two curls and compare responses:
```
curl 'https://fallingfruit.org/api/0.3/locations?api_key=SECRET&muni=true&invasive=false&zoom=14&bounds=51.83916742177383,17.944342723146917|51.86092652178794,17.915112676853077&limit=250' | jq -r 'map("\(.id) \(.lat) \(.lng)")'
curl 'https://fallingfruit.org/api/0.3/locations?api_key=SECRET&muni=true&invasive=false&zoom=14&bounds=51.83916742177383,17.944342723146917|51.86092652178794,17.915112676853077&center=51.85004828675768,17.929727699999997&limit=250' | jq -r 'map("\(.id) \(.lat) \(.lng)")'
```

```
[
  "1995785 51.85266630000001 17.904963900000002",
  "1995784 51.85254640000001 17.908129699999993",
  "1995699 51.8517985 17.9149896",
  "1993621 51.846542 16.598745",
  "1908703 51.843443892997655 -2.6748382916445124",
  "1830430 51.849896 -0.660943",
  "1829833 51.83991804170566 -2.272583864038533",
  "1829464 51.84839479863793 1.2680188763356481",
  "1814217 51.843775 0.892054",
  "1814216 51.845754 0.894311",
  "1810203 51.84755142473063 1.248438853981897",
  "1810201 51.843910409624854 1.2434373863544046",
  "1810200 51.844223291594744 1.2447834083971498",
  "1810199 51.844568098943576 1.2450316907863979",
  "1810198 51.844520714261 1.2449304454996835",
  "1810202 51.847144836239615 1.248217617372065",
  "1805350 51.849378 -8.436396",
  "1805348 51.849378 -8.436396",
  "1805347 51.849071 -8.435247",
  "1772057 51.857385 5.849662",
  "1767193 51.852143 0.16158",
  "1766113 51.85397 -2.654662",
  "1766106 51.859324077414016 -1.4561261824755745",
  "1761709 51.849823 17.967217",
  "1721480 51.844634 -3.050637",
  "1592271 51.859584 -2.207764",
  "1523695 51.852155 0.149147",
  "608232 51.855461 0.951111",
  "663662 51.8608 0.959883",
  "608240 51.852203 0.965745",
  "608233 51.859173 0.95418",
  "608231 51.859333 0.959448",
  "1517289 51.85322 -2.242386",
  "608230 51.85878 0.965386",
  "608226 51.856789 0.956669"
]
[
  "1761566 51.851354 17.933361",
  "1761565 51.850225 17.936143",
  "1761564 51.846593 17.925377",
  "1761563 51.851904 17.921251",
  "1761567 51.851876 17.919989",
  "1830533 51.854601 17.920746",
  "1761568 51.851896 17.918087",
  "1761562 51.85363 17.918532",
  "1995699 51.8517985 17.9149896"
]
```

**Comment by ezwelty** [comment]
This is somewhere between a bug and user error :wink: Indeed the queries are different, and in one case the bounds order does not matter, in the other it does. If you change your bounds to `swlat,swlng|nelat,nelng`, then it works as expected.

`51.83916742177383,17.915112676853077|51.86092652178794,17.944342723146917`

I could ignore order and take min and max, or I could be strict and reject the input if not in the right order. What do you think?

**Comment by wbazant** [comment]
Ah yes the parameters were in the wrong order, thanks! I checked out the branch I was working on (https://github.com/falling-fruit/falling-fruit-web/pull/543 ), searched for a place in the list view, looked at the network tab, and it does the query in the correct order - it must have been some mad intermediate version that had the parameters swapped.

> I could ignore order and take min and max, or I could be strict and reject the input if not in the right order. What do you think?

In general I'd go for a version of the second one - a piece of advice I've read on this a long time ago was to "parse, don't validate" so there would be a function somewhere that takes a string and produces a rectangle, or fails with the message about how it wants the input.

So with 'parse don't validate' these would all return the same error:
```
curl 'https://fallingfruit.org/api/0.3/locations?api_key=SECRET&muni=true&invasive=false&zoom=14&bounds=pancake&limit=250'
curl 'https://fallingfruit.org/api/0.3/locations?api_key=SECRET&muni=true&invasive=false&zoom=14&bounds=pancake51.83916742177383,17.915112676853077|51.86092652178794,17.944342723146
917&limit=250'
curl 'https://fallingfruit.org/api/0.3/locations?api_key=SECRET&muni=true&invasive=false&zoom=14&bounds=51.83916742177383,17.944342723146917|51.86092652178794,17.915112676853077&limit=250'
```
but doesn't really matter! Thanks for explaining my error again.

Actually, to go a level further, I'd have the API ask for north / east / south / west of the rectangle and then there's no string to split, but no need to change it.
