### ISSUE TITLE
Add user_id for GET /location/:locationId

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-api#45]
Came up in [#504. ](https://github.com/falling-fruit/falling-fruit-web/issues/504) - we'd like the location pages to link to user pages.

I can see in the API documentation that reviews have both author and user_id associated - could we have user_id for the location too?

**Comment by ezwelty** [comment]
@wbazant It already is, but I updated the documentation where it had been accidentally omitted.

https://fallingfruit.org/api/0.3/locations/3383?api_key=<API_KEY>
